### ISSUE TITLE
Unable to set systemPort

### ISSUE THREAD

**Issue by hw131313** [appium/appium-uiautomator2-driver#687] opened 2023-10-31 13:25 UTC
Package version:
appium-uiautomator2-driver: 2.33.0

Capabilities
```
{
      "platformName": "Android",
      "appium:udid": "localhost:5317",
      "appium:appPackage": "com.bluestacks.settings",
      "appium:noReset": true,
      "appium:automationName": "UiAutomator2",
      "appium:appActivity": "com.bluestacks.settings.SettingsActivity",
      "appium:systemPort": 8300,
}
``` 

<details><summary>Appium Log</summary>
<p>

[AndroidUiautomator2Driver@3d48] Creating session with W3C capabilities: {
[AndroidUiautomator2Driver@3d48]   "alwaysMatch": {
[AndroidUiautomator2Driver@3d48]     "platformName": "Android",
[AndroidUiautomator2Driver@3d48]     "appium:udid": "localhost:5317",
[AndroidUiautomator2Driver@3d48]     "appium:appPackage": "com.bluestacks.settings",
[AndroidUiautomator2Driver@3d48]     "appium:noReset": true,
[AndroidUiautomator2Driver@3d48]     "appium:automationName": "UiAutomator2",
[AndroidUiautomator2Driver@3d48]     "appium:appActivity": "com.bluestacks.settings.SettingsActivity",
[AndroidUiautomator2Driver@3d48]     "appium:systemPort": 8300
[AndroidUiautomator2Driver@3d48]   },
[AndroidUiautomator2Driver@3d48]   "firstMatch": [
[AndroidUiautomator2Driver@3d48]     {}
[AndroidUiautomator2Driver@3d48]   ]
[AndroidUiautomator2Driver@3d48] }
[AndroidUiautomator2Driver@3d48 (7401e532)] Session created with session id: 7401e532-a3eb-4b94-a8b0-8f24e3d37641
[AndroidUiautomator2Driver@3d48 (7401e532)] Starting 'com.bluestacks.settings' directly on the device
[ADB] Found 3 'build-tools' folders under 'C:\Android\Sdk' (newest first):
[ADB]     C:\Android\Sdk\build-tools\31.0.0
[ADB]     C:\Android\Sdk\build-tools\30.0.3
[ADB]     C:\Android\Sdk\build-tools\28.0.3
[ADB] Using 'adb.exe' from 'C:\Android\Sdk\platform-tools\adb.exe'
[ADB] Running 'C:\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[AndroidDriver] Retrieving device list
[ADB] Trying to find connected Android devices
[ADB] Getting connected devices
[ADB] Connected devices: [{"udid":"localhost:5317","state":"device"}]
[AndroidDriver] Using device: localhost:5317
[ADB] Using 'adb.exe' from 'C:\Android\Sdk\platform-tools\adb.exe'
[ADB] Running 'C:\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[ADB] Setting device id to localhost:5317
[ADB] Running 'C:\Android\Sdk\platform-tools\adb.exe -P 5037 -s localhost:5317 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 28
[ADB] Getting device platform version
[ADB] Running 'C:\Android\Sdk\platform-tools\adb.exe -P 5037 -s localhost:5317 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 9
[ADB] Device API level: 28
[AndroidUiautomator2Driver@3d48 (7401e532)] Relaxing hidden api policy
[ADB] Running 'C:\Android\Sdk\platform-tools\adb.exe -P 5037 -s localhost\:5317 shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1''
[AndroidDriver] No app sent in, not parsing package/activity
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running 'C:\Android\Sdk\platform-tools\adb.exe -P 5037 -s localhost:5317 shell dumpsys package io.appium.settings'
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('5.2.0' >= '5.2.0')
[ADB] There is no need to install/upgrade 'D:\Code\demo\node_modules\.pnpm\io.appium.settings@5.2.0\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running 'C:\Android\Sdk\platform-tools\adb.exe -P 5037 -s localhost\:5317 shell 'pgrep --help; echo $?''
[ADB] Running 'C:\Android\Sdk\platform-tools\adb.exe -P 5037 -s localhost:5317 shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[ADB] Running 'C:\Android\Sdk\platform-tools\adb.exe -P 5037 -s localhost:5317 shell appops set io.appium.settings android:mock_location allow'
[ADB] Running 'C:\Android\Sdk\platform-tools\adb.exe -P 5037 -s localhost\:5317 shell "[ -e '/data/local/tmp/mock_apps.json' ] && echo __PASS__"'
[ADB] Running 'C:\Android\Sdk\platform-tools\adb.exe -P 5037 -s localhost:5317 shell cat /data/local/tmp/mock_apps.json'
[Logcat] Starting logs capture with command: C:\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s localhost\:5317 logcat -v threadtime
[AndroidUiautomator2Driver@3d48 (7401e532)] Forwarding UiAutomator2 Server port 6790 to local port 8200
[ADB] Forwarding system: 8200 to device: 6790
[ADB] Running 'C:\Android\Sdk\platform-tools\adb.exe -P 5037 -s localhost:5317 forward tcp:8200 tcp:6790'

</p>
</details>

**Comment by mykola-mokhnach** [comment] 2023-10-31 17:48
Yes, it looks like a regression. Should be fixed by the above PR

**Closed** 2023-10-31 20:29 UTC
