### ISSUE TITLE
Services to be available timeout

### ISSUE THREAD

**Issue by tranduyminh91** [appium/appium-uiautomator2-driver#445] opened 2021-03-03 05:32 UTC
I got appium log:
**[debug] [35m[UiAutomator2][39m Waiting up to 30000ms for services to be available**

I need increase this timeout, I tried everytimeout that I know but not successful. Please help

**Comment by KazuCocoa** [comment] 2021-03-03 07:20
Duplicate of https://github.com/appium/appium/issues/15152

**Closed by KazuCocoa** 2021-03-03 07:20 UTC
